# Generated by Django 5.0.6 on 2025-07-01 20:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursos_updated_alter_cursos_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['created'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='cursos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de actualización'),
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualización')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descripción')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Cursos')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'ordering': ['created'],
            },
        ),
    ]
