# Generated by Django 5.0.6 on 2025-07-16 14:20

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_cursos_options_alter_cursos_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.cursos', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción Actividad'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Clave Actividad'),
        ),
    ]
