# Generated by Django 5.0.6 on 2025-07-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_actividades_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='descripcion',
            field=models.TextField(default='Curso descriptado', max_length=100, verbose_name='Descripción Curso'),
        ),
    ]
