# Generated by Django 5.0.6 on 2025-07-17 15:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_cursos_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['nombre'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterField(
            model_name='cursos',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='Descripción detallada del curso.', verbose_name='Descripción del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='duracion',
            field=models.IntegerField(default=0, verbose_name='Duración (horas)'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='estatus',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Imagen del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
    ]
