# Generated by Django 5.0.6 on 2025-07-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_alter_cursos_options_alter_cursos_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Curso'),
        ),
    ]
