# Generated by Django 5.0.6 on 2025-07-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_alter_cursos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='image',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
    ]
